services:
  ngrok:
    image: ngrok/ngrok:latest
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--log=stdout"
      - "--log-level=info"
      - "host.docker.internal:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: bridge
    ports:
      - "4040:4040"